name: Python Standalone Tests
permissions:
  contents: read
  pull-requests: read
on:
  push:
    branches:
      - '/**'
      - '!github-action-test-workflow'
  pull_request:
    branches:
      - '/**'
      - '!github-action-test-workflow'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Check out the AIMS UI repository
    - name: Checkout repository
      uses: actions/checkout@v2
  
    # Set up Python environment 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_test.txt

    - name: Install the UI as a python package
      run: |
        pip install -e .

    # Run Python tests
    - name: Run Python Standalone Tests
      run: |
        python3 -m pytest tests/pytest_tests/aims_ui

